In [1]:
import numpy as np

In [2]:
print("basic array creation")

basic array creation


In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a=[1,2,3,5,"hello"]
a

[1, 2, 3, 5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3', '5', 'hello'], dtype='<U21')

In [6]:
l=[[1,2,3],[4,6,7],[8,7,8]]
l

[[1, 2, 3], [4, 6, 7], [8, 7, 8]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 6, 7],
       [8, 7, 8]])

In [8]:
print("array generating function")

array generating function


In [14]:
arr=np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [20]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
arr=np.linspace(1,5,2)
arr

array([1., 5.])

In [22]:
print("random generating function")

random generating function


In [23]:
np.random.rand(10) #normalisation

array([0.66092218, 0.97971551, 0.55435068, 0.16071855, 0.27296852,
       0.04087353, 0.91454399, 0.3163853 , 0.34136941, 0.77484882])

In [24]:
np.random.randn(10)  #standaristaion  -3,3 ke beech


array([-1.70922986,  0.56974086, -2.04334924,  1.07566302,  0.15468533,
       -0.95163469,  2.16261273,  1.0498027 , -0.63997577,  2.57558246])

In [25]:
np.random.randint(6)

4

In [26]:
np.random.randint(10,20,10)

array([19, 14, 11, 18, 18, 17, 17, 14, 15, 12], dtype=int32)

In [27]:
print("attributes")

attributes


In [29]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.shape

(3, 3)

In [31]:
arr.size

9

In [32]:
arr.dtype

dtype('int64')

In [33]:
print("array methods")

array methods


In [34]:
arr.min()

np.int64(1)

In [35]:
arr.max()

np.int64(9)

In [36]:
arr.sum()

np.int64(45)

In [37]:
np.sum(arr,axis=0) #column wise sum

array([12, 15, 18])

In [38]:
np.sum(arr,axis=1) #row wise sum

array([ 6, 15, 24])

In [39]:
arr.mean()

np.float64(5.0)

In [40]:
arr.std()

np.float64(2.581988897471611)

In [41]:
arr.argmax() #max element ka index

np.int64(8)

In [42]:
arr.argmin() #min element ka index

np.int64(0)

In [43]:
print("reshaping and resizing")

reshaping and resizing


In [45]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])