In [1]:
print("array operation")

array operation


In [2]:
import numpy as np

In [3]:
print("arithmetic operation")

arithmetic operation


In [5]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [6]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [7]:
a1-a2

array([-5, -5, -5, -5, -5])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

In [11]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [12]:
print("broadcasting")

broadcasting


In [15]:
l=[10,20,30]
arr=np.array(l)

In [16]:
arr+10

array([20, 30, 40])

In [17]:
print("deep and shallow copy")

deep and shallow copy


In [18]:
a=np.arange(1,21)

In [20]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [21]:
a
b=a.copy() #making shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
print("matrix operation")

matrix operation


In [34]:
A=np.array([[1,2],[4,5]])
B=np.array([[1,2],[4,5]])
A


array([[1, 2],
       [4, 5]])

In [35]:
B

array([[1, 2],
       [4, 5]])

In [36]:
A @ B  # we can use this too - np.dot(A,B)

array([[ 9, 12],
       [24, 33]])

In [37]:
A.T

array([[1, 4],
       [2, 5]])

In [38]:
print("advance array manipulation")

advance array manipulation


In [39]:
print("stacking array")

stacking array


In [40]:
A

array([[1, 2],
       [4, 5]])

In [41]:
B

array([[1, 2],
       [4, 5]])

In [42]:
# You cannot stack two matrix so A and B cant be stacked we can stack vector

In [43]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [44]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [47]:
print("splitting array")

splitting array


In [50]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]