In [1]:
import numpy as np

In [2]:
print("numpy indexing and slicing of vectors")

numpy indexing and slicing of vectors


In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:5]

array([11, 12, 13, 14, 15])

In [9]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[2:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[3::2]

array([14, 16, 18, 20])

In [12]:
print("numpy indexing and slicing of matrix")

numpy indexing and slicing of matrix


In [14]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0]

array([1, 2, 3, 4, 5])

In [17]:
arr[0,4]

np.int64(5)

In [19]:
slice=arr[0:2,1:3]   #specific portion of matrix
slice

array([[2, 3],
       [7, 8]])

In [23]:
slice1=arr[3:,3:]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [25]:
print("boolean indexing")

boolean indexing


In [27]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool=arr%2==0
bool

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr=arr[bool]
arr

array([12, 14, 16, 18, 20])